// Inventory
export const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";
export const REMOVE_INVENTORY_ITEM = "REMOVE_INVENTORY_ITEM";
export const CHECKOUT_INVENTORY_ITEM = "CHECKOUT_INVENTORY_ITEM";
export const GET_ITEMS = "GET_ITEMS";

// Employees
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
